name: Full Stack CI/CD Pipeline

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    # ... steps for testing backend services would be here

  test_frontend:
    runs-on: ubuntu-latest
    # ... steps for testing frontend would be here

  build_backend_images:
    runs-on: ubuntu-latest
    needs: [test_backend] # Only runs if backend tests pass
    # ... steps to build & push product/order service images
      steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

    - name: Build and Push Product Service Image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/product_service:latest ./backend/product_service/
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/product_service:latest

    - name: Build and Push Order Service Image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/order_service:latest ./backend/order_service/
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/order_service:latest

    - name: Logout from Azure
      run: az logout
      if: always()

  build_frontend_image:
    runs-on: ubuntu-latest
    needs: [test_frontend] # Only runs if frontend tests pass
    # ... steps to build & push the frontend image

  deploy_infrastructure:
    runs-on: ubuntu-latest
    needs: [build_backend_images, build_frontend_image] # Needs all images
    if: github.ref == 'refs/heads/main' # CRITICAL: ONLY RUN THIS JOB ON THE MAIN BRANCH
    # ... steps to deploy DBs, configmaps, secrets

  deploy_backend_services:
    runs-on: ubuntu-latest
    needs: [deploy_infrastructure] # Needs DBs to be running first
    if: github.ref == 'refs/heads/main'
    # ... steps to deploy product/order services & wait for their IPs

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: [deploy_backend_services] # Needs backend IPs from the previous job
    if: github.ref == 'refs/heads/main'
    # ... steps to deploy the frontend