name: Full Stack CI/CD Pipeline

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    # ... steps for testing backend services would be here

  test_frontend:
    runs-on: ubuntu-latest
    # ... steps for testing frontend would be here

  build_backend_images:
    runs-on: ubuntu-latest
    needs: [test_backend] # Only runs if backend tests pass
    # ... steps to build & push product/order service images

  build_frontend_image:
    runs-on: ubuntu-latest
    needs: [test_frontend] # Only runs if frontend tests pass
    # ... steps to build & push the frontend image

  deploy_infrastructure:
    runs-on: ubuntu-latest
    needs: [build_backend_images, build_frontend_image] # Needs all images
    if: github.ref == 'refs/heads/main' # CRITICAL: ONLY RUN THIS JOB ON THE MAIN BRANCH
    # ... steps to deploy DBs, configmaps, secrets

  deploy_backend_services:
    runs-on: ubuntu-latest
    needs: [deploy_infrastructure] # Needs DBs to be running first
    if: github.ref == 'refs/heads/main'
    # ... steps to deploy product/order services & wait for their IPs

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: [deploy_backend_services] # Needs backend IPs from the previous job
    if: github.ref == 'refs/heads/main'
    # ... steps to deploy the frontend