# week08/.github/workflows/frontend-cd.yml

name: CD - Deploy Frontend to AKS

on:
  workflow_dispatch:
    inputs:
      product_api_ip:
        description: 'External IP of Product Service'
        required: true
        default: 'http://<ip_address>:8000'
      order_api_ip:
        description: 'External IP of Order Service (e.g., http://Y.Y.Y.Y:8001)'
        required: true
        default: 'http://<ip_address>:8001'
      aks_cluster_name:
        description: 'Name of the AKS Cluster to deploy to'
        required: true
        default: 'sit722-week8-aks'
      aks_resource_group:
        description: 'Resource Group of the AKS Cluster'
        required: true
        default: 'sit722-week8-rg'

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry (Fixed)
        run: |
          # Get ACR login server URL properly
          LOGIN_SERVER=$(az acr show --name ${{ secrets.AZURE_CONTAINER_REGISTRY }} --query loginServer --output tsv)
          echo "ACR Login Server: $LOGIN_SERVER"
          
          # Login using Docker with service principal credentials
          CLIENT_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')
          CLIENT_SECRET=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientSecret')
          
          docker login $LOGIN_SERVER --username $CLIENT_ID --password $CLIENT_SECRET
      
      - name: Skip IP injection (Manual configuration)
        run: |
          echo "Skipping IP injection - ensure main.js has correct IPs manually"
          echo "Product API: ${{ inputs.product_api_ip }}"
          echo "Order API: ${{ inputs.order_api_ip }}"
      
      - name: Build and Push Frontend Image
        run: |
          # Get ACR login server URL
          LOGIN_SERVER=$(az acr show --name ${{ secrets.AZURE_CONTAINER_REGISTRY }} --query loginServer --output tsv)
          
          docker build -t $LOGIN_SERVER/frontend:latest ./frontend/
          docker push $LOGIN_SERVER/frontend:latest
      
      - name: Set Kubernetes context
        run: |
          az aks get-credentials --resource-group ${{ inputs.aks_resource_group }} --name ${{ inputs.aks_cluster_name }} --overwrite-existing

      - name: Deploy Frontend to AKS
        run: |
          echo "Deploying frontend to AKS cluster: ${{ inputs.aks_cluster_name }}"
          kubectl apply -f k8s/frontend.yaml
      
      - name: Logout from Azure
        run: az logout
